chore: tune CI/CD

diff --git a/.github/workflows/package_analyze.yaml b/.github/workflows/package_analyze.yaml
--- a/.github/workflows/package_analyze.yaml
+++ b/.github/workflows/package_analyze.yaml
@@ -105,12 +105,25 @@ jobs:
           CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
         if: success()
         run: |
-          dart test --coverage=coverage --concurrency=2
+          dart test --concurrency=2 --coverage=coverage --reporter=github --file-reporter="json:reports/tests.json"
           dart run coverage:format_coverage --in coverage --out coverage/coverage.lcov --lcov --report-on=lib
           dart run tool/uncovered_coverage.dart
           dart test test/fake_test.dart --coverage=coverage --concurrency=2
           dart run coverage:format_coverage --in coverage --out coverage/coverage.lcov --lcov --report-on=lib
           bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
+
+      - name: Publish test results
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Tests result
+          path: action_app/reports/tests.json
+          reporter: dart-json
+          list-suites: "all"
+          list-tests: "all"
+          max-annotations: 16
+          fail-on-error: true
+          token: ${{ secrets.GITHUB_TOKEN }}
 
   check-minimal-supported-dart-compatibility:
     needs: analysis
@@ -162,7 +175,7 @@ jobs:
       - name: Check compatibility
         run: |
           dart analyze --fatal-warnings --fatal-infos .
-          dart test --concurrency=2
+          dart test --concurrency=2 --reporter=github
 
   check-windows-compatibility:
     needs: analysis
@@ -183,4 +196,4 @@ jobs:
       - name: Check compatibility
         run: |
           dart analyze --fatal-warnings --fatal-infos .
-          dart test --concurrency=2
+          dart test --concurrency=2 --reporter=github
